### ISSUE TITLE
prerelease version bump: vA.B.C-rcD, not vA.B.C-rcD.(N+1)

### ISSUE THREAD

**Issue by behaghel** [skyglobal/component-helper#37]
when doing a *prerelease*:
- if we are currently in v0.1.2, next prerelease should be v0.1.3-rc1
- if we are currently in v0.1.0-rc3, prerelease should bump to v0.1.0-rc4

**Comment by peter-mouland** [comment]
looks like this is how the `semVer` plug expects to work.  Looks like pre-release version should be in the format `v.0.1.2-rc.0` so that the bump will then work as expected.

https://github.com/npm/node-semver#prerelease-tags
