### ISSUE TITLE
new component has odd output

### ISSUE THREAD

**Issue by georgerichmond** [skyglobal/component-helper#41]
Not quite sure what is going on here:

`Creating new component firebase-blog
prompt: GitHub Repository SSH URL:

Copying Component Files ...

Github Repository URL must be a url`

**Comment by peter-mouland** [comment]
looks like an old version (v1.0.0 will ask for your git ssh last)

**Comment by georgerichmond** [comment]
Ah right how do I update?

**Comment by georgerichmond** [comment]
Boom. Thanks Pete!
