### ISSUE TITLE
No syntax checking for project name

### ISSUE THREAD

**Issue by georgerichmond** [skyglobal/component-helper#42]
If you enter a project name with an invalid character (like a hyphen) then the app blows up when it tries to load. This is because the demo app name just takes the name entered. Probably good to convert separated words into camel case?

Happy to look at this later, just raising it on here first for discussion.

**Comment by peter-mouland** [comment]
in the `mian.require.js` file we did
```
var local = {}; local['{{ component }}']
```
looks a bit funny if you dont know why it is doing it, but this would be a quick sollution for the `spec/main.js` and `demo.js`.  Your suggestion makes sense, just might have some unexpected side-affects so might take longer

**Comment by rosswarren** [comment]
Just ran into this issue and came to raise it, then saw it is already raised here!
