### ISSUE TITLE
Create MIGRATION.md

### ISSUE THREAD

**Issue by behaghel** [skyglobal/component-helper#85]
I have been caught between 1.1.0 to 1.2.0 with this breaking change: `directoryPrefix: ''` had to become `target: pkg.name + '/' + pkg.version + '/'`. I think we need to provide a migration guide for each breaking change. If this document is well structured we could use that as a warning / error message on the CLI when we detect the migration hasn't been performed.

**Comment by peter-mouland** [comment]
my bad - i tried to make it backwards compatible - obviously forgetting about the pkg.name and version that are still required
https://github.com/skyglobal/component-helper/blob/master/tasks/release.js#L31
