### ISSUE TITLE
task method all() has become run()

### ISSUE THREAD

**Issue by behaghel** [skyglobal/component-helper#87]
The doc regarding gulp and the sample files need to be updated to reflect that.

We also need to add this consideration as an item for the migration guide, see #86.

**Comment by peter-mouland** [comment]
documentation fixed in #90.

i'd think i'd prefer either a PR to allow backwards compatability (i.e. add an `.all()` that simply calls `.run()`). this should probably be a bug fix and released as v1.2.1 rather than waiting for v1.3.0
