### ISSUE TITLE
change `release:'s3'`to `release:['gh-pages','s3']`

### ISSUE THREAD

**Issue by peter-mouland** [skyglobal/component-helper#92]
there are some projects that want to release to gh-page, but dont have s3 setup.
there will be some that want to release to heroku, but not s3 or gh-pages as it wont be a static app.

This would be another **breaking change** :s 

Thoughts?

**Comment by behaghel** [comment]
:+1: makes a lot of sense to me.

**Comment by peter-mouland** [comment]
fixed by #95
