### ISSUE TITLE
bigger in size and incompatible with angular between 0.9.2 and 1.2.0

### ISSUE THREAD

**Issue by behaghel** [skyglobal/component-helper#93]
I migrated sky-tags to use the component-helper v1.2.x series and all went well. But then I did the next release I did, it wouldn't load it in our Angular app. Even more bizarre, we had literally no way to understand why: the whole app wouldn't load with a cryptic message like: 
```
main.js:1 Uncaught TypeError: undefined is not a function
main.js:1(anonymous function)
``` 

The previous release worked really well for them and this one only had a new feature and the new version of the component-helper. I noticed that the files produced by this new version are way bigger than for 0.9.2:

 helper version | size | file
-------------------  | ----- | -----
 0.9.2 | 180k | sky-tags.js
 1.2.0 | 265k | sky-tags.js
 0.9.2 | 107k | sky-tags.min.js
 1.2.0 | 153k | sky-tags.min.js

In this experiment, nothing changes but the component-helper version and the related changes due to non-backward compatible elements in the config.

It would be good to understand why as it could give a lead as to where the incompatibility with Angular is happening.

**Comment by peter-mouland** [comment]
Initial thoughts are the browserify options, includeGlobals etc. they add
loads extra to file size. That's where I'd start anyway!

**Comment by behaghel** [comment]
Thank you Pete. You were right!
